version: '3.7'

services:

  tl_code:
    build:
      context: ./code
      args:
        - tl_release=${TL_RELEASE}
        - tl_version=${TL_VERSION}
        - tl_download_base=${TL_DOWNLOAD_BASE}
        - tl_download_file=${TL_DOWNLOAD_FILE}
    image:  lczub/testlink_code:${TL_RELEASE}
    container_name: testlink_code

  tl_pg:
    depends_on:
     - tl_code
    build:
      context: ./db
      args:
        - tl_release=${TL_RELEASE}
        - tl_version=${TL_VERSION}
        - tl_pg_version=${TL_PG_VERSION}
   
  tl_apache:
    depends_on:
      - tl_pg
    build:
      context: ./webapp
      args:
        - tl_release=${TL_RELEASE}
        - tl_version=${TL_VERSION}
        - tl_php_version=${TL_PHP_VERSION}

