version: '3.7'

services:

  tl_pg:
    image:  lczub/testlink_pg:${TL_PG_VERSION}-${TL_RELEASE}
    container_name: testlink_pg_${TL_RELEASE}
    environment:
      POSTGRES_PASSWORD: ${TL_DB_USER}
      POSTGRES_USER: ${TL_DB_PASSWORD}
      POSTGRES_DB: ${TL_DB_NAME}
    volumes:
      - tl-pg-volume:/var/lib/postgresql/data

  tl_smtp:
    image:  mailhog/mailhog
    container_name: testlink_smtp_${TL_RELEASE}
    ports:
      - ${TL_SMTP_PORT_MH_SMTP_SERVER}:1025
      - ${TL_SMTP_PORT_MH_HTTP_SERVER}:8025

  tl_apache:
    depends_on:
      - tl_pg
    image:  lczub/testlink_apache_php:${TL_PHP_VERSION}-${TL_RELEASE}
    container_name: testlink_apache_${TL_RELEASE}
    environment:
      TL_DB_USER: ${TL_DB_USER}
      TL_DB_PASSWORD: ${TL_DB_PASSWORD}
      TL_DB_HOST: ${TL_DB_HOST}
      TL_DB_NAME: ${TL_DB_NAME}
    volumes:
      - tl-data-volume:/var/testlink
    ports:
      - ${TL_APACHE_PORT}:80
      
volumes:
  tl-data-volume:
    name: ${TL_VOLUME_NAME_DATA}
  tl-pg-volume:
    name: ${TL_VOLUME_NAME_PG}    
    